encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'encyclopedia'
urlpatterns = [
    path("", views.index, name="index"),
    path ("search", views.search, name="search"),
    path ("new_page", views.new_page, name="new_page"),
    path ("random_page", views.random_page, name="random_page"),
    path("<str:title>/edit", views.edit, name="edit"),
    path ("<str:title>", views.entry, name="title"),
]

mail/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    # API Routes
    path("emails", views.compose, name="compose"),
    path("emails/<int:email_id>", views.email, name="email"),
    path("emails/<str:mailbox>", views.mailbox, name="mailbox"),
]

workspace/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("hello/", include ("hello.urls")),
    path ("newyear/", include ("newyear.urls")),
    path ("tasks/", include ("tasks.urls")),
    path ('encyclopedia/', include ('encyclopedia.urls')),
    path ("mail/", include ("mail.urls")),
    path ("flights/", include ("flights.urls")),
    path ("users", include ("users.urls")),
]

encyclopedia/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from . import util

import random
import re


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


from . import convert
def entry (request, title):

    # Get the entry
    entry = util.get_entry (title)

    if not entry:
        # display error page
        return render (request, "encyclopedia/error.html")

    # CONVERT MARKDOWN TO HTML
    html = convert.heading (entry)
    html = convert.paragraphs(html)
    html = convert.external_link (html)
    html = convert.internal_link (html)
    html = convert.boldface_text (html)
    
    # display the entry page
    return render (request, "encyclopedia/entry.html", {
        "title": title,
        "entry": html,
    })



def search (request):
    
    # Get the query and remove whitespace and convert to lowercase
    query = request.GET["q"].strip().lower()

    # If the query is empty
    if not query:
        # display the error page
        return render (request, "encyclopedia/error.html")

    # Get all entries
    entries = util.list_entries()

    # create a empty set
    cleaned_entries = set ()

    # convert all the entries to lowercase and add to the set
    for entry in entries:
        cleaned_entries.add (entry.lower())

    # Keep track entries that have the query as a substring
    entry_set = set()

    # If the query in entries
    if query in cleaned_entries:
        # redirect user to the entry page
        return HttpResponseRedirect (reverse("encyclopedia:title", args=[query]))
    else:
        for entry in cleaned_entries:
            # if query is substring of entries
            if query in entry:
                # collect those entries
                entry_set.add (entry)        
        
        if (entry_set):
            # display the entry set
            return render (request, "encyclopedia/search_results.html", {
                "entry_set": entry_set,
            })
        else:
            return render (request, "encyclopedia/error.html")
    


def new_page (request):
    if request.method == 'POST':
        
        # Get the title and content and remove the whitespace
        title = request.POST["title"].strip()
        content = request.POST["content"].strip()
        
        # Check to see title or content provided
        if (not title):
            message = "Empty Page!"
            return render (request, "encyclopedia/new_page.html", {
                "message": message,
            })


        # make the title to lowercase
        cleaned_title = title.lower()

        # Combine title with content
        content = f"#{title}\n{content}"

        # Get all the entries
        entries = util.list_entries()

        # make all the entries to lower case and add to the set
        cleaned_entries = set ()
        for entry in entries:
            cleaned_entries.add(entry.lower())
        
        # Check to see entry is already in the set
        if cleaned_title in cleaned_entries:
            return render (request, "encyclopedia/error.html", {
                "message": "Page already exist!"
            })
        
        # save the entry to disk
        util.save_entry (cleaned_title, content)

        # Go to new entry page
        return HttpResponseRedirect (reverse ("encyclopedia:new_page"))

    return render(request, "encyclopedia/new_page.html")



def random_page (request):
    # Get all entries
    entries = util.list_entries ()

    # Get random entry 
    num = random.randint (0, len(entries) - 1)
    random_entry = entries[num]

    # Redirect to that entry page
    return HttpResponseRedirect (reverse ("encyclopedia:title", args=[random_entry]))




def edit (request, title):

    if request.method == 'POST':

        # Get the edited entry
        edited_entry =  request.POST["content"]
        
        # Remove new lines
        cleaned_entry = edited_entry.replace ("\r", "")

        # save edited entry to disk
        util.save_entry (title, cleaned_entry)

        # redirect to the edited entry
        return HttpResponseRedirect (reverse ("encyclopedia:title", args=[title]))


    # Get the entry 
    entry = util.get_entry (title)

    # render html page with entry
    return render (request, "encyclopedia/edit_page.html", {
        "entry": entry,
        "title": title,
    })

encyclopedia/templates/encyclopedia/edit_page.html
{% extends 'encyclopedia/layout.html' %}


{% block title %}
	Edit 
{% endblock %}

{% block body %}

<h1 class="text-muted">Edit Page</h1>
<div class="edit_area">
	<form action={% url 'encyclopedia:edit' title %} method="post" >
		{% csrf_token %}
		<textarea class="edit-area" name="content">{{ entry }}</textarea>
		<input type="submit" value="save" class="btn btn-info  save"/>
		<textarea class="hide_area"></textarea>
	</form>
</div>

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
		Entry
{% endblock %}

{% block body %}
		{{ entry| safe }}

		<div class="edit-area">
			<a class="btn btn-info  edit_button edit" href="/encyclopedia/{{ title }}/edit">Edit</a>
		</div>

{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
		Error
{% endblock %}

{% block body %}
<div class="alert-container">
		{% if message %}
		<br />
			<div class="alert alert-danger error" role="alert">
				{{ message }}
			</div>
		{% else %}
			<div class="alert alert-danger error" role="alert">
				Page Not Found!
			</div>
</div>
		{% endif %}
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
	<h1 class="text-muted"> All Pages </h1>
    <ul class="list-group list-group-flush">
        {% for entry in entries %}
				<li class="list-group-item"><a class="entry" href="{% url 'encyclopedia:title' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
			<div class="row">

				<div class="sidebar col-lg-2 col-md-3">

					<h1 class="logo">WIKI</h1>

					<form action="{% url 'encyclopedia:search' %}" method="get"  >
							<input class="search form-control" type="text" name="q" placeholder="Search Encyclopedia...">
					</form>

						<ul class="nav">
							<li class="nav-item">
								<a class="nav-link" href="{% url 'encyclopedia:index' %}">🏠 Home</a>
							</li>

							<li class="nav-item">
								<a class="nav-link" href="{% url 'encyclopedia:new_page' %}">📄 New Page</a>
							</li>
			
							<li class="nav-item">
								<a class="nav-link" href="{% url 'encyclopedia:random_page' %}">📜 Random Page</a>
							</li>
						</ul>

					{% block nav %}
					{% endblock %}

				</div>

				<div class="main col-lg-10 col-md-9">
						{% block body %}
						{% endblock %}
				</div>

			</div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new_page.html
{% extends 'encyclopedia/layout.html' %}


{% block titel %}
	New Page
{% endblock %}


{% block body %}
<div class="new_page_area">
		<h1 class="text-muted">New Page</h1>
		<hr />
		


		<div class="new_page_form">
			<form action="{% url 'encyclopedia:new_page' %}" method="post" >
				{% csrf_token %}
				<input name="title" type="text" placeholder="title..." class="form-control title"></input>
				<textarea name="content" placeholder="entry..." class="content-area "></textarea>
				<input type="submit" value="Create" class="btn btn-info  create ">

		{% if message %}
			<div class="alert alert-warning new_page_error" role="alert">
					{{ message }}
			</div>
		{% endif %}

				<textarea class="hide"></textarea>
			</form>
		</div>
<div>
{% endblock %}

encyclopedia/templates/encyclopedia/search_results.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
	search results
{% endblock %}

{% block body %}
<h1 class="text-muted">Search Result...</h1>
	<ul class="list-group list-group-flush">	
		{% for entry in entry_set %}
		<li class="list-group-item"><a href="{% url 'encyclopedia:title' entry %}">{{ entry }}</a></li>	
		{% endfor %}
		<textarea class="hide"></textarea>
	</ul>


{% endblock %}